### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by whyuu** [ShiftMediaProject/libiconv#1]
## Context
shiftmediaproject\libilbc\rtc_base\checks.h(57,10): fatal error C1083: 无法打开包括文件: “absl/meta/type_traits.h”: No such file or directory (编译源文件 ..\common_audio\signal_processing\dot_product_with_scale.cc)
shiftmediaproject\libilbc\rtc_base\checks.h(57,10): fatal error C1083: 无法打开包括文件: “absl/meta/type_traits.h”: No such file or directory (编译源文件 ..\rtc_base\checks.cc)

## Steps to Reproduce
1.   open resolution
2.   select  release dll
3.   build 

## Your Environment
win10 + vs2019  

## Possible Fix
config.h is missing

**Comment by Sibras** [comment]
The error you listed clearly states 'libilbc' but youve created a ticket for 'libiconv'. Please correct your issue. Make sure you are only using the build solutions in the SMP folder as no other ones are supported

**Comment by whyuu** [comment]
sorry,  I submitted an issue that is not part of this project
